version: "3.8"

services:
  db:
    build: .
    container_name: trace-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tracedb
      POSTGRES_USER: traceuser
      POSTGRES_PASSWORD: tracepass

volumes:
  pgdata: